// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::transform_result_dco;
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.0.0-dev.21";

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire_ArchiveServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ArchiveServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::archive::ArchiveServices::new())
                })())
            }
        },
    )
}
fn wire_ArchiveServices_zip_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ArchiveServices_zip",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::archive::ArchiveServices>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::archive::ArchiveServices::zip(&api_that))
                })())
            }
        },
    )
}
fn wire_init_logger_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_logger",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_log_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::common::init_logger(api_log_dir))
                })())
            }
        },
    )
}
fn wire_ContigServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ContigServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::contig::ContigServices::new())
                })())
            }
        },
    )
}
fn wire_ContigServices_summarize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ContigServices_summarize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::contig::ContigServices>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::contig::ContigServices::summarize(&api_that))
                })())
            }
        },
    )
}
fn wire_RawReadServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RawReadServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::reads::RawReadServices::new())
                })())
            }
        },
    )
}
fn wire_RawReadServices_summarize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "RawReadServices_summarize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::reads::RawReadServices>::sse_decode(&mut deserializer);
            let api_mode = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::reads::RawReadServices::summarize(
                        &api_that, api_mode,
                    ))
                })())
            }
        },
    )
}
fn wire_AlignmentServices_concat_alignment_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "AlignmentServices_concat_alignment",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::AlignmentServices>::sse_decode(&mut deserializer);
            let api_out_fname = <String>::sse_decode(&mut deserializer);
            let api_out_fmt_str = <String>::sse_decode(&mut deserializer);
            let api_partition_fmt = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::AlignmentServices::concat_alignment(
                        &api_that,
                        api_out_fname,
                        api_out_fmt_str,
                        api_partition_fmt,
                    ))
                })())
            }
        },
    )
}
fn wire_AlignmentServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "AlignmentServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::AlignmentServices::new())
                })())
            }
        },
    )
}
fn wire_AlignmentServices_summarize_alignment_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "AlignmentServices_summarize_alignment",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::AlignmentServices>::sse_decode(&mut deserializer);
            let api_output_prefix = <String>::sse_decode(&mut deserializer);
            let api_interval = <usize>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(
                        crate::api::sequence::AlignmentServices::summarize_alignment(
                            &api_that,
                            api_output_prefix,
                            api_interval,
                        ),
                    )
                })())
            }
        },
    )
}
fn wire_FilteringServices_filter_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FilteringServices_filter",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::FilteringServices>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::FilteringServices::filter(&api_that))
                })())
            }
        },
    )
}
fn wire_FilteringServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "FilteringServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::FilteringServices::new())
                })())
            }
        },
    )
}
fn wire_PartitionServices_convert_partition_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "PartitionServices_convert_partition",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::PartitionServices>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::PartitionServices::convert_partition(
                        &api_that,
                    ))
                })())
            }
        },
    )
}
fn wire_PartitionServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "PartitionServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::PartitionServices::new())
                })())
            }
        },
    )
}
fn wire_SequenceExtraction_extract_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceExtraction_extract",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that =
                <crate::api::sequence::SequenceExtraction>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceExtraction::extract(
                        &api_that,
                    ))
                })())
            }
        },
    )
}
fn wire_SequenceExtraction_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceExtraction_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceExtraction::new())
                })())
            }
        },
    )
}
fn wire_SequenceRemoval_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceRemoval_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceRemoval::new())
                })())
            }
        },
    )
}
fn wire_SequenceRemoval_remove_sequence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceRemoval_remove_sequence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::SequenceRemoval>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceRemoval::remove_sequence(
                        &api_that,
                    ))
                })())
            }
        },
    )
}
fn wire_SequenceRenaming_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceRenaming_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceRenaming::new())
                })())
            }
        },
    )
}
fn wire_SequenceRenaming_rename_sequence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceRenaming_rename_sequence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::SequenceRenaming>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceRenaming::rename_sequence(
                        &api_that,
                    ))
                })())
            }
        },
    )
}
fn wire_SequenceServices_convert_sequence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceServices_convert_sequence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::SequenceServices>::sse_decode(&mut deserializer);
            let api_output_fmt = <String>::sse_decode(&mut deserializer);
            let api_sort = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceServices::convert_sequence(
                        &api_that,
                        api_output_fmt,
                        api_sort,
                    ))
                })())
            }
        },
    )
}
fn wire_SequenceServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceServices::new())
                })())
            }
        },
    )
}
fn wire_SequenceServices_parse_sequence_id_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceServices_parse_sequence_id",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::SequenceServices>::sse_decode(&mut deserializer);
            let api_output_fname = <String>::sse_decode(&mut deserializer);
            let api_is_map = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceServices::parse_sequence_id(
                        &api_that,
                        api_output_fname,
                        api_is_map,
                    ))
                })())
            }
        },
    )
}
fn wire_SequenceServices_translate_sequence_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SequenceServices_translate_sequence",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that = <crate::api::sequence::SequenceServices>::sse_decode(&mut deserializer);
            let api_table = <String>::sse_decode(&mut deserializer);
            let api_reading_frame = <usize>::sse_decode(&mut deserializer);
            let api_output_fmt = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SequenceServices::translate_sequence(
                        &api_that,
                        api_table,
                        api_reading_frame,
                        api_output_fmt,
                    ))
                })())
            }
        },
    )
}
fn wire_SplitAlignmentServices_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SplitAlignmentServices_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::SplitAlignmentServices::new())
                })())
            }
        },
    )
}
fn wire_SplitAlignmentServices_split_alignment_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "SplitAlignmentServices_split_alignment",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_that =
                <crate::api::sequence::SplitAlignmentServices>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(
                        crate::api::sequence::SplitAlignmentServices::split_alignment(&api_that),
                    )
                })())
            }
        },
    )
}
fn wire_show_dna_uppercase_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "show_dna_uppercase",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse((move || {
                    Result::<_, ()>::Ok(crate::api::sequence::show_dna_uppercase())
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::sequence::AlignmentServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        return crate::api::sequence::AlignmentServices {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
        };
    }
}

impl SseDecode for crate::api::archive::ArchiveServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        return crate::api::archive::ArchiveServices {
            output_path: var_outputPath,
            input_files: var_inputFiles,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::contig::ContigServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_files = <Vec<String>>::sse_decode(deserializer);
        let mut var_fileFmt = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        return crate::api::contig::ContigServices {
            files: var_files,
            file_fmt: var_fileFmt,
            output_dir: var_outputDir,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::sequence::FilteringParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                return crate::api::sequence::FilteringParams::MinTax(var_field0);
            }
            1 => {
                let mut var_field0 = <usize>::sse_decode(deserializer);
                return crate::api::sequence::FilteringParams::AlnLen(var_field0);
            }
            2 => {
                let mut var_field0 = <usize>::sse_decode(deserializer);
                return crate::api::sequence::FilteringParams::ParsInf(var_field0);
            }
            3 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                return crate::api::sequence::FilteringParams::PercInf(var_field0);
            }
            4 => {
                let mut var_field0 = <Vec<String>>::sse_decode(deserializer);
                return crate::api::sequence::FilteringParams::TaxonAll(var_field0);
            }
            5 => {
                return crate::api::sequence::FilteringParams::None;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::sequence::FilteringServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_isConcat = <bool>::sse_decode(deserializer);
        let mut var_params = <crate::api::sequence::FilteringParams>::sse_decode(deserializer);
        let mut var_outputFmt = <Option<String>>::sse_decode(deserializer);
        let mut var_prefix = <Option<String>>::sse_decode(deserializer);
        let mut var_partitionFmt = <Option<String>>::sse_decode(deserializer);
        return crate::api::sequence::FilteringServices {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
            is_concat: var_isConcat,
            params: var_params,
            output_fmt: var_outputFmt,
            prefix: var_prefix,
            partition_fmt: var_partitionFmt,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<String>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::sequence::PartitionServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputPartFmt = <String>::sse_decode(deserializer);
        let mut var_output = <String>::sse_decode(deserializer);
        let mut var_outputPartFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_isUncheck = <bool>::sse_decode(deserializer);
        return crate::api::sequence::PartitionServices {
            input_files: var_inputFiles,
            input_part_fmt: var_inputPartFmt,
            output: var_output,
            output_part_fmt: var_outputPartFmt,
            datatype: var_datatype,
            is_uncheck: var_isUncheck,
        };
    }
}

impl SseDecode for crate::api::reads::RawReadServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_files = <Vec<String>>::sse_decode(deserializer);
        let mut var_fileFmt = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        return crate::api::reads::RawReadServices {
            files: var_files,
            file_fmt: var_fileFmt,
            output_dir: var_outputDir,
        };
    }
}

impl SseDecode for crate::api::sequence::SequenceExtraction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_outputFmt = <String>::sse_decode(deserializer);
        let mut var_params =
            <crate::api::sequence::SequenceExtractionParams>::sse_decode(deserializer);
        return crate::api::sequence::SequenceExtraction {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
            output_fmt: var_outputFmt,
            params: var_params,
        };
    }
}

impl SseDecode for crate::api::sequence::SequenceExtractionParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <Vec<String>>::sse_decode(deserializer);
                return crate::api::sequence::SequenceExtractionParams::Id(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::sequence::SequenceExtractionParams::File(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::sequence::SequenceExtractionParams::Regex(var_field0);
            }
            3 => {
                return crate::api::sequence::SequenceExtractionParams::None;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::sequence::SequenceRemoval {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_outputFmt = <String>::sse_decode(deserializer);
        let mut var_removeRegex = <Option<String>>::sse_decode(deserializer);
        let mut var_removeList = <Option<Vec<String>>>::sse_decode(deserializer);
        return crate::api::sequence::SequenceRemoval {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
            output_fmt: var_outputFmt,
            remove_regex: var_removeRegex,
            remove_list: var_removeList,
        };
    }
}

impl SseDecode for crate::api::sequence::SequenceRenaming {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_outputFmt = <String>::sse_decode(deserializer);
        let mut var_params =
            <crate::api::sequence::SequenceRenamingParams>::sse_decode(deserializer);
        return crate::api::sequence::SequenceRenaming {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
            output_fmt: var_outputFmt,
            params: var_params,
        };
    }
}

impl SseDecode for crate::api::sequence::SequenceRenamingParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::sequence::SequenceRenamingParams::RenameId(var_field0);
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::sequence::SequenceRenamingParams::RemoveStr(var_field0);
            }
            2 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                let mut var_field1 = <bool>::sse_decode(deserializer);
                return crate::api::sequence::SequenceRenamingParams::RemoveRegex(
                    var_field0, var_field1,
                );
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                let mut var_field1 = <String>::sse_decode(deserializer);
                return crate::api::sequence::SequenceRenamingParams::ReplaceStr(
                    var_field0, var_field1,
                );
            }
            4 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                let mut var_field1 = <String>::sse_decode(deserializer);
                let mut var_field2 = <bool>::sse_decode(deserializer);
                return crate::api::sequence::SequenceRenamingParams::ReplaceRegex(
                    var_field0, var_field1, var_field2,
                );
            }
            5 => {
                return crate::api::sequence::SequenceRenamingParams::None;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::sequence::SequenceServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFiles = <Vec<String>>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        return crate::api::sequence::SequenceServices {
            input_files: var_inputFiles,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            output_dir: var_outputDir,
        };
    }
}

impl SseDecode for crate::api::sequence::SplitAlignmentServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputFile = <String>::sse_decode(deserializer);
        let mut var_inputFmt = <String>::sse_decode(deserializer);
        let mut var_datatype = <String>::sse_decode(deserializer);
        let mut var_inputPartition = <Option<String>>::sse_decode(deserializer);
        let mut var_inputPartitionFmt = <String>::sse_decode(deserializer);
        let mut var_outputDir = <String>::sse_decode(deserializer);
        let mut var_prefix = <Option<String>>::sse_decode(deserializer);
        let mut var_outputFmt = <String>::sse_decode(deserializer);
        let mut var_isUncheck = <bool>::sse_decode(deserializer);
        return crate::api::sequence::SplitAlignmentServices {
            input_file: var_inputFile,
            input_fmt: var_inputFmt,
            datatype: var_datatype,
            input_partition: var_inputPartition,
            input_partition_fmt: var_inputPartitionFmt,
            output_dir: var_outputDir,
            prefix: var_prefix,
            output_fmt: var_outputFmt,
            is_uncheck: var_isUncheck,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire_ArchiveServices_new_impl(port, ptr, rust_vec_len, data_len),
        2 => wire_ArchiveServices_zip_impl(port, ptr, rust_vec_len, data_len),
        3 => wire_init_logger_impl(port, ptr, rust_vec_len, data_len),
        4 => wire_ContigServices_new_impl(port, ptr, rust_vec_len, data_len),
        5 => wire_ContigServices_summarize_impl(port, ptr, rust_vec_len, data_len),
        6 => wire_RawReadServices_new_impl(port, ptr, rust_vec_len, data_len),
        7 => wire_RawReadServices_summarize_impl(port, ptr, rust_vec_len, data_len),
        14 => wire_AlignmentServices_concat_alignment_impl(port, ptr, rust_vec_len, data_len),
        13 => wire_AlignmentServices_new_impl(port, ptr, rust_vec_len, data_len),
        15 => wire_AlignmentServices_summarize_alignment_impl(port, ptr, rust_vec_len, data_len),
        19 => wire_FilteringServices_filter_impl(port, ptr, rust_vec_len, data_len),
        18 => wire_FilteringServices_new_impl(port, ptr, rust_vec_len, data_len),
        21 => wire_PartitionServices_convert_partition_impl(port, ptr, rust_vec_len, data_len),
        20 => wire_PartitionServices_new_impl(port, ptr, rust_vec_len, data_len),
        27 => wire_SequenceExtraction_extract_impl(port, ptr, rust_vec_len, data_len),
        26 => wire_SequenceExtraction_new_impl(port, ptr, rust_vec_len, data_len),
        22 => wire_SequenceRemoval_new_impl(port, ptr, rust_vec_len, data_len),
        23 => wire_SequenceRemoval_remove_sequence_impl(port, ptr, rust_vec_len, data_len),
        24 => wire_SequenceRenaming_new_impl(port, ptr, rust_vec_len, data_len),
        25 => wire_SequenceRenaming_rename_sequence_impl(port, ptr, rust_vec_len, data_len),
        10 => wire_SequenceServices_convert_sequence_impl(port, ptr, rust_vec_len, data_len),
        9 => wire_SequenceServices_new_impl(port, ptr, rust_vec_len, data_len),
        11 => wire_SequenceServices_parse_sequence_id_impl(port, ptr, rust_vec_len, data_len),
        12 => wire_SequenceServices_translate_sequence_impl(port, ptr, rust_vec_len, data_len),
        16 => wire_SplitAlignmentServices_new_impl(port, ptr, rust_vec_len, data_len),
        17 => wire_SplitAlignmentServices_split_alignment_impl(port, ptr, rust_vec_len, data_len),
        8 => wire_show_dna_uppercase_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::AlignmentServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::AlignmentServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::AlignmentServices>
    for crate::api::sequence::AlignmentServices
{
    fn into_into_dart(self) -> crate::api::sequence::AlignmentServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::archive::ArchiveServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.input_files.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::archive::ArchiveServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::archive::ArchiveServices>
    for crate::api::archive::ArchiveServices
{
    fn into_into_dart(self) -> crate::api::archive::ArchiveServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::contig::ContigServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.files.into_into_dart().into_dart(),
            self.file_fmt.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::contig::ContigServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::contig::ContigServices>
    for crate::api::contig::ContigServices
{
    fn into_into_dart(self) -> crate::api::contig::ContigServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::FilteringParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::sequence::FilteringParams::MinTax(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::FilteringParams::AlnLen(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::FilteringParams::ParsInf(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::FilteringParams::PercInf(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::FilteringParams::TaxonAll(field0) => {
                [4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::FilteringParams::None => [5.into_dart()].into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::FilteringParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::FilteringParams>
    for crate::api::sequence::FilteringParams
{
    fn into_into_dart(self) -> crate::api::sequence::FilteringParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::FilteringServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.is_concat.into_into_dart().into_dart(),
            self.params.into_into_dart().into_dart(),
            self.output_fmt.into_into_dart().into_dart(),
            self.prefix.into_into_dart().into_dart(),
            self.partition_fmt.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::FilteringServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::FilteringServices>
    for crate::api::sequence::FilteringServices
{
    fn into_into_dart(self) -> crate::api::sequence::FilteringServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::PartitionServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_part_fmt.into_into_dart().into_dart(),
            self.output.into_into_dart().into_dart(),
            self.output_part_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.is_uncheck.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::PartitionServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::PartitionServices>
    for crate::api::sequence::PartitionServices
{
    fn into_into_dart(self) -> crate::api::sequence::PartitionServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::reads::RawReadServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.files.into_into_dart().into_dart(),
            self.file_fmt.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::reads::RawReadServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::reads::RawReadServices>
    for crate::api::reads::RawReadServices
{
    fn into_into_dart(self) -> crate::api::reads::RawReadServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceExtraction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.output_fmt.into_into_dart().into_dart(),
            self.params.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceExtraction
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceExtraction>
    for crate::api::sequence::SequenceExtraction
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceExtraction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceExtractionParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::sequence::SequenceExtractionParams::Id(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::SequenceExtractionParams::File(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::SequenceExtractionParams::Regex(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::SequenceExtractionParams::None => [3.into_dart()].into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceExtractionParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceExtractionParams>
    for crate::api::sequence::SequenceExtractionParams
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceExtractionParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceRemoval {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.output_fmt.into_into_dart().into_dart(),
            self.remove_regex.into_into_dart().into_dart(),
            self.remove_list.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceRemoval
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceRemoval>
    for crate::api::sequence::SequenceRemoval
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceRemoval {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceRenaming {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.output_fmt.into_into_dart().into_dart(),
            self.params.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceRenaming
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceRenaming>
    for crate::api::sequence::SequenceRenaming
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceRenaming {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceRenamingParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::sequence::SequenceRenamingParams::RenameId(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::SequenceRenamingParams::RemoveStr(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::sequence::SequenceRenamingParams::RemoveRegex(field0, field1) => [
                2.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sequence::SequenceRenamingParams::ReplaceStr(field0, field1) => [
                3.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sequence::SequenceRenamingParams::ReplaceRegex(field0, field1, field2) => [
                4.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
                field2.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::sequence::SequenceRenamingParams::None => [5.into_dart()].into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceRenamingParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceRenamingParams>
    for crate::api::sequence::SequenceRenamingParams
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceRenamingParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SequenceServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_files.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SequenceServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SequenceServices>
    for crate::api::sequence::SequenceServices
{
    fn into_into_dart(self) -> crate::api::sequence::SequenceServices {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::sequence::SplitAlignmentServices {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_file.into_into_dart().into_dart(),
            self.input_fmt.into_into_dart().into_dart(),
            self.datatype.into_into_dart().into_dart(),
            self.input_partition.into_into_dart().into_dart(),
            self.input_partition_fmt.into_into_dart().into_dart(),
            self.output_dir.into_into_dart().into_dart(),
            self.prefix.into_into_dart().into_dart(),
            self.output_fmt.into_into_dart().into_dart(),
            self.is_uncheck.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::sequence::SplitAlignmentServices
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::sequence::SplitAlignmentServices>
    for crate::api::sequence::SplitAlignmentServices
{
    fn into_into_dart(self) -> crate::api::sequence::SplitAlignmentServices {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::sequence::AlignmentServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
    }
}

impl SseEncode for crate::api::archive::ArchiveServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <Vec<String>>::sse_encode(self.input_files, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::contig::ContigServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.files, serializer);
        <String>::sse_encode(self.file_fmt, serializer);
        <String>::sse_encode(self.output_dir, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::sequence::FilteringParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::sequence::FilteringParams::MinTax(field0) => {
                <i32>::sse_encode(0, serializer);
                <f64>::sse_encode(field0, serializer);
            }
            crate::api::sequence::FilteringParams::AlnLen(field0) => {
                <i32>::sse_encode(1, serializer);
                <usize>::sse_encode(field0, serializer);
            }
            crate::api::sequence::FilteringParams::ParsInf(field0) => {
                <i32>::sse_encode(2, serializer);
                <usize>::sse_encode(field0, serializer);
            }
            crate::api::sequence::FilteringParams::PercInf(field0) => {
                <i32>::sse_encode(3, serializer);
                <f64>::sse_encode(field0, serializer);
            }
            crate::api::sequence::FilteringParams::TaxonAll(field0) => {
                <i32>::sse_encode(4, serializer);
                <Vec<String>>::sse_encode(field0, serializer);
            }
            crate::api::sequence::FilteringParams::None => {
                <i32>::sse_encode(5, serializer);
            }
        }
    }
}

impl SseEncode for crate::api::sequence::FilteringServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <bool>::sse_encode(self.is_concat, serializer);
        <crate::api::sequence::FilteringParams>::sse_encode(self.params, serializer);
        <Option<String>>::sse_encode(self.output_fmt, serializer);
        <Option<String>>::sse_encode(self.prefix, serializer);
        <Option<String>>::sse_encode(self.partition_fmt, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<String>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<String>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::sequence::PartitionServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_part_fmt, serializer);
        <String>::sse_encode(self.output, serializer);
        <String>::sse_encode(self.output_part_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <bool>::sse_encode(self.is_uncheck, serializer);
    }
}

impl SseEncode for crate::api::reads::RawReadServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.files, serializer);
        <String>::sse_encode(self.file_fmt, serializer);
        <String>::sse_encode(self.output_dir, serializer);
    }
}

impl SseEncode for crate::api::sequence::SequenceExtraction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.output_fmt, serializer);
        <crate::api::sequence::SequenceExtractionParams>::sse_encode(self.params, serializer);
    }
}

impl SseEncode for crate::api::sequence::SequenceExtractionParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::sequence::SequenceExtractionParams::Id(field0) => {
                <i32>::sse_encode(0, serializer);
                <Vec<String>>::sse_encode(field0, serializer);
            }
            crate::api::sequence::SequenceExtractionParams::File(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::sequence::SequenceExtractionParams::Regex(field0) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::sequence::SequenceExtractionParams::None => {
                <i32>::sse_encode(3, serializer);
            }
        }
    }
}

impl SseEncode for crate::api::sequence::SequenceRemoval {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.output_fmt, serializer);
        <Option<String>>::sse_encode(self.remove_regex, serializer);
        <Option<Vec<String>>>::sse_encode(self.remove_list, serializer);
    }
}

impl SseEncode for crate::api::sequence::SequenceRenaming {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <String>::sse_encode(self.output_fmt, serializer);
        <crate::api::sequence::SequenceRenamingParams>::sse_encode(self.params, serializer);
    }
}

impl SseEncode for crate::api::sequence::SequenceRenamingParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::sequence::SequenceRenamingParams::RenameId(field0) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::sequence::SequenceRenamingParams::RemoveStr(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            crate::api::sequence::SequenceRenamingParams::RemoveRegex(field0, field1) => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(field0, serializer);
                <bool>::sse_encode(field1, serializer);
            }
            crate::api::sequence::SequenceRenamingParams::ReplaceStr(field0, field1) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
                <String>::sse_encode(field1, serializer);
            }
            crate::api::sequence::SequenceRenamingParams::ReplaceRegex(field0, field1, field2) => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(field0, serializer);
                <String>::sse_encode(field1, serializer);
                <bool>::sse_encode(field2, serializer);
            }
            crate::api::sequence::SequenceRenamingParams::None => {
                <i32>::sse_encode(5, serializer);
            }
        }
    }
}

impl SseEncode for crate::api::sequence::SequenceServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.input_files, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <String>::sse_encode(self.output_dir, serializer);
    }
}

impl SseEncode for crate::api::sequence::SplitAlignmentServices {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_file, serializer);
        <String>::sse_encode(self.input_fmt, serializer);
        <String>::sse_encode(self.datatype, serializer);
        <Option<String>>::sse_encode(self.input_partition, serializer);
        <String>::sse_encode(self.input_partition_fmt, serializer);
        <String>::sse_encode(self.output_dir, serializer);
        <Option<String>>::sse_encode(self.prefix, serializer);
        <String>::sse_encode(self.output_fmt, serializer);
        <bool>::sse_encode(self.is_uncheck, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
#[path = "frb_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "frb_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use web::*;
