// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.74.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class Api {
  Future<String> showDnaUppercase({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kShowDnaUppercaseConstMeta;

  Future<ConcatParser> newStaticMethodConcatParser({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodConcatParserConstMeta;

  Future<void> concatAlignmentMethodConcatParser(
      {required ConcatParser that, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kConcatAlignmentMethodConcatParserConstMeta;
}

class ConcatParser {
  final Api bridge;
  final String dirPath;
  final String fileFmt;
  final String datatype;
  final String output;
  final String outputFmt;
  final String partitionFmt;

  const ConcatParser({
    required this.bridge,
    required this.dirPath,
    required this.fileFmt,
    required this.datatype,
    required this.output,
    required this.outputFmt,
    required this.partitionFmt,
  });

  static Future<ConcatParser> newConcatParser(
          {required Api bridge, dynamic hint}) =>
      bridge.newStaticMethodConcatParser(hint: hint);

  Future<void> concatAlignment({dynamic hint}) =>
      bridge.concatAlignmentMethodConcatParser(
        that: this,
      );
}

class ApiImpl implements Api {
  final ApiPlatform _platform;
  factory ApiImpl(ExternalLibrary dylib) => ApiImpl.raw(ApiPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory ApiImpl.wasm(FutureOr<WasmModule> module) =>
      ApiImpl(module as ExternalLibrary);
  ApiImpl.raw(this._platform);
  Future<String> showDnaUppercase({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_show_dna_uppercase(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kShowDnaUppercaseConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kShowDnaUppercaseConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "show_dna_uppercase",
        argNames: [],
      );

  Future<ConcatParser> newStaticMethodConcatParser({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_new__static_method__ConcatParser(port_),
      parseSuccessData: (d) => _wire2api_concat_parser(d),
      constMeta: kNewStaticMethodConcatParserConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kNewStaticMethodConcatParserConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "new__static_method__ConcatParser",
        argNames: [],
      );

  Future<void> concatAlignmentMethodConcatParser(
      {required ConcatParser that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_concat_parser(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_concat_alignment__method__ConcatParser(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kConcatAlignmentMethodConcatParserConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kConcatAlignmentMethodConcatParserConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "concat_alignment__method__ConcatParser",
            argNames: ["that"],
          );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  ConcatParser _wire2api_concat_parser(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ConcatParser(
      bridge: this,
      dirPath: _wire2api_String(arr[0]),
      fileFmt: _wire2api_String(arr[1]),
      datatype: _wire2api_String(arr[2]),
      output: _wire2api_String(arr[3]),
      outputFmt: _wire2api_String(arr[4]),
      partitionFmt: _wire2api_String(arr[5]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class ApiPlatform extends FlutterRustBridgeBase<ApiWire> {
  ApiPlatform(ffi.DynamicLibrary dylib) : super(ApiWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_ConcatParser> api2wire_box_autoadd_concat_parser(
      ConcatParser raw) {
    final ptr = inner.new_box_autoadd_concat_parser_0();
    _api_fill_to_wire_concat_parser(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_concat_parser(
      ConcatParser apiObj, ffi.Pointer<wire_ConcatParser> wireObj) {
    _api_fill_to_wire_concat_parser(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_concat_parser(
      ConcatParser apiObj, wire_ConcatParser wireObj) {
    wireObj.dir_path = api2wire_String(apiObj.dirPath);
    wireObj.file_fmt = api2wire_String(apiObj.fileFmt);
    wireObj.datatype = api2wire_String(apiObj.datatype);
    wireObj.output = api2wire_String(apiObj.output);
    wireObj.output_fmt = api2wire_String(apiObj.outputFmt);
    wireObj.partition_fmt = api2wire_String(apiObj.partitionFmt);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class ApiWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ApiWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ApiWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_show_dna_uppercase(
    int port_,
  ) {
    return _wire_show_dna_uppercase(
      port_,
    );
  }

  late final _wire_show_dna_uppercasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_show_dna_uppercase');
  late final _wire_show_dna_uppercase =
      _wire_show_dna_uppercasePtr.asFunction<void Function(int)>();

  void wire_new__static_method__ConcatParser(
    int port_,
  ) {
    return _wire_new__static_method__ConcatParser(
      port_,
    );
  }

  late final _wire_new__static_method__ConcatParserPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_new__static_method__ConcatParser');
  late final _wire_new__static_method__ConcatParser =
      _wire_new__static_method__ConcatParserPtr
          .asFunction<void Function(int)>();

  void wire_concat_alignment__method__ConcatParser(
    int port_,
    ffi.Pointer<wire_ConcatParser> that,
  ) {
    return _wire_concat_alignment__method__ConcatParser(
      port_,
      that,
    );
  }

  late final _wire_concat_alignment__method__ConcatParserPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_ConcatParser>)>>(
      'wire_concat_alignment__method__ConcatParser');
  late final _wire_concat_alignment__method__ConcatParser =
      _wire_concat_alignment__method__ConcatParserPtr
          .asFunction<void Function(int, ffi.Pointer<wire_ConcatParser>)>();

  ffi.Pointer<wire_ConcatParser> new_box_autoadd_concat_parser_0() {
    return _new_box_autoadd_concat_parser_0();
  }

  late final _new_box_autoadd_concat_parser_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_ConcatParser> Function()>>(
          'new_box_autoadd_concat_parser_0');
  late final _new_box_autoadd_concat_parser_0 =
      _new_box_autoadd_concat_parser_0Ptr
          .asFunction<ffi.Pointer<wire_ConcatParser> Function()>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

class wire_ConcatParser extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> dir_path;

  external ffi.Pointer<wire_uint_8_list> file_fmt;

  external ffi.Pointer<wire_uint_8_list> datatype;

  external ffi.Pointer<wire_uint_8_list> output;

  external ffi.Pointer<wire_uint_8_list> output_fmt;

  external ffi.Pointer<wire_uint_8_list> partition_fmt;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
