// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LocusSummaryServices {
  final String inputPath;

  const LocusSummaryServices({
    required this.inputPath,
  });

  Future<int> getLine({dynamic hint}) =>
      RustLib.instance.api.locusSummaryServicesGetLine(
        that: this,
      );

  static Future<LocusSummaryServices> newLocusSummaryServices(
          {required String inputPath, dynamic hint}) =>
      RustLib.instance.api
          .locusSummaryServicesNew(inputPath: inputPath, hint: hint);

  Future<Map<String, int>> parseColumns(
          {required String colName, dynamic hint}) =>
      RustLib.instance.api.locusSummaryServicesParseColumns(
        that: this,
        colName: colName,
      );

  @override
  int get hashCode => inputPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocusSummaryServices &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath;
}
