// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RawReadServices {
  final List<String> files;
  final String fileFmt;
  final String outputDir;

  const RawReadServices({
    required this.files,
    required this.fileFmt,
    required this.outputDir,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RawReadServices> newInstance({dynamic hint}) =>
      RustLib.instance.api.crateApiReadsRawReadServicesNew(hint: hint);

  Future<void> summarize(
          {required String mode, String? prefix, dynamic hint}) =>
      RustLib.instance.api.crateApiReadsRawReadServicesSummarize(
          that: this, mode: mode, prefix: prefix, hint: hint);

  @override
  int get hashCode => files.hashCode ^ fileFmt.hashCode ^ outputDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawReadServices &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          fileFmt == other.fileFmt &&
          outputDir == other.outputDir;
}
